updated pipelines

diff --git a/.github/workflows/cd.yml b/.github/workflows/cd.yml
--- a/.github/workflows/cd.yml
+++ b/.github/workflows/cd.yml
@@ -3,10 +3,12 @@ name: CD
 on:
   workflow_dispatch:
   workflow_run:
-    workflows: ["CI"] #Should run only after CI
+    workflows: ["CI"]
     types:
       - completed
   pull_request:
+    branches:
+      - develop
   push:
     branches:
       - main
@@ -41,15 +43,26 @@ jobs:
             FINAL_VERSION="${{ env.VERSION }}-beta-${GITHUB_SHA::8}"
           elif [[ "${{ github.event_name }}" == "push" && "${{ github.ref }}" == "refs/heads/main" ]]; then
             FINAL_VERSION="${{ env.VERSION }}"
+          else
+            FINAL_VERSION=""
           fi
           echo "FINAL_VERSION=${FINAL_VERSION}" >> $GITHUB_ENV
           echo "Final version set: $FINAL_VERSION"
+
+      - name: Check Final Version
+        run: |
+          if [[ -z "${{ env.FINAL_VERSION }}" ]]; then
+            echo "Error: Version number is null. Publish steps will be skipped."
+            exit 1
+          fi
 
       - name: Pack
         run: dotnet pack --configuration Release --output ./output /p:PackageVersion=${{ env.FINAL_VERSION }}
 
       - name: Publish to NuGet
+        if: ${{ env.FINAL_VERSION != '' }}
         run: dotnet nuget push ./output/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
 
       - name: Publish to GitHub Packages
+        if: ${{ env.FINAL_VERSION != '' }}
         run: dotnet nuget push ./output/*.nupkg --api-key ${{ secrets.CI_CD }} --source "https://nuget.pkg.github.com/Rades98/index.json" --skip-duplicate
diff --git a/.github/workflows/pr.yml b/.github/workflows/pr.yml
--- a/.github/workflows/pr.yml
+++ b/.github/workflows/pr.yml
@@ -28,6 +28,25 @@ jobs:
           else
             echo "Branch is allowed to merge to develop."
           fi
+
+      - name: Validate Commit Messages
+        run: |
+          invalid_commits=0
+          while IFS= read -r commit; do
+            message="${commit##* }"
+            if [[ ${#message} -le 5 ]]; then
+              echo "Invalid commit message: $message. Must be longer than 5 characters."
+              invalid_commits=$((invalid_commits+1))
+            fi
+          done < <(git log origin/${{ github.event.pull_request.base.ref }}..HEAD --pretty=format:'%H %s')
+
+          if [[ $invalid_commits -gt 0 ]]; then
+            echo "$invalid_commits commit(s) have invalid messages."
+            exit 1
+          else
+            echo "All commit messages are valid."
+          fi
+
   label:
     runs-on: ubuntu-latest
     permissions:
